# GitHub Actions Workflow that generates Rustdocs for HotStuff-rs every time a commit is pushed to a branch
# or a stable release or pre-release is released, and then pushes this Rustdocs to the master branch of the
# [hotstuff_rs_docs](https://github.com/parallelchain-io/hotstuff_rs_docs) repository so that it may
# automatically be deployed to GitHub Pages.

name: Deploy complete Rustdocs
run-name: Deploy docs for branch/release `${{ github.ref }}` to GitHub Pages.

# List of events that trigger the deploying of Rustdocs.
on:
    # Receiving a push to any branch.
    push:

    # Releasing a prerelease or stable release.
    release:
        types:
            - prereleased
            - released

jobs:
    build_docs:
        name: Build rustdocs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout updated `hotstuff_rs` ref 
              uses: actions/checkout@v4
        
            - name: Install Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1 

            - name: Generate complete rustdocs 
              run: cargo doc --document-private-items --no-deps 

            - name: Upload rustdocs as `complete_docs` artifact
              uses: actions/upload-artifact@v4
              with:
                name: complete_docs
                path: target/doc/

    push_docs:
        name: Push rustdocs to `hotstuff_rs_docs` repository
        runs-on: ubuntu-latest
        needs: build_docs
        steps:
            - name: Checkout latest `hotstuff_rs_docs`
              uses: actions/checkout@v4
              with:
                repository: parallelchain-io/hotstuff_rs_docs
                fetch-depth: 0
                token: ${{ secrets.HOTSTUFF_RS_DOCS_PUSHER }}

            - id: compute_subfolder_path
              name: Compute path to the subfolder the docs should be in 
              run: |
                subfolder_path=$GITHUB_REF_TYPE/$GITHUB_REF_NAME/
                echo "subfolder_path=$subfolder_path" >> $GITHUB_OUTPUT
              env:
                  GITHUB_REF_TYPE: "${{ github.ref_type }}"
                  GITHUB_REF_NAME: "${{ github.ref_name }}"

            - name: Prepare the subfolder
              run: |
                if [ -d $SUBFOLDER_PATH ]; then
                    echo "Subfolder `$SUB_FOLDER_PATH` already exists, clearing its contents"
                    rm -rf "${SUBFOLDER_PATH:?}/"*
                else
                    echo "Subfolder `$SUBFOLDER_PATH` doesn't exist yet. Creating it"
                    mkdir -p "$SUBFOLDER_PATH"
                fi
              env:
                SUBFOLDER_PATH: ${{ steps.compute_subfolder_path.outputs.subfolder_path }}
            
            - name: Download `complete_docs` artifact to the subfolder
              uses: actions/download-artifact@v4 
              with:
                name: complete_docs
                path: ${{ steps.compute_subfolder_path.outputs.subfolder_path }}

            - name: Stage and commit the changes to `hotstuff_rs_docs`
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git add .
                git commit -a -m "$COMMIT_MESSAGE"
              env: 
                COMMIT_MESSAGE: "add docs for branch/release `${{ github.ref }}`"

            - name: Push the changes to `hotstuff_rs_docs` to the remote
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.HOTSTUFF_RS_DOCS_PUSHER }}
                repository: parallelchain-io/hotstuff_rs_docs
